// src/converters/docx-converter-fidelity.spec.ts

import test from "ava";
import { convertDocxToMarkdown } from "./docx-converter.js";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const FIXTURES = join(__dirname, "../../test-fixtures/docx-fidelity");

/**
 * Fidelity test using the Calibre demo.docx — a real-world document with
 * rich formatting (headings, tables, lists, code blocks, blockquotes, etc.).
 *
 * The expected output was generated by get-md's DOCX converter and saved
 * as a reference. This test ensures the converter produces consistent output
 * across changes.
 */
test("Calibre demo.docx fidelity", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const expected = readFileSync(
    join(FIXTURES, "calibre-demo-expected.md"),
    "utf-8",
  );

  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  t.is(result.markdown, expected);
});

/**
 * Structural sanity checks on the Calibre demo output.
 * These test specific formatting features without requiring exact string match.
 */
test("Calibre demo.docx: headings are present", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  // Should have h1 and h2 headings
  t.true(result.markdown.includes("# "), "has at least one heading");
  t.true(result.markdown.includes("## "), "has at least one h2");
});

test("Calibre demo.docx: bold formatting preserved", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  // Bold text appears as **bold,** or **bold-italic,** etc.
  t.true(result.markdown.includes("**bold"), "has bold text");
});

test("Calibre demo.docx: italic formatting preserved", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  // Italic text appears as *italic,* etc.
  t.true(result.markdown.includes("*italic"), "has italic text");
});

test("Calibre demo.docx: tables are present", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  t.true(result.markdown.includes("|"), "has table pipes");
  t.true(result.markdown.includes("---"), "has table separators");
});

test("Calibre demo.docx: word count is reasonable", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  // The Calibre demo has ~2000+ words
  t.true(
    (result.metadata.wordCount ?? 0) > 1000,
    `word count should be > 1000, got ${result.metadata.wordCount}`,
  );
});

test("Calibre demo.docx: output is non-trivial length", async (t) => {
  const docxBuffer = readFileSync(join(FIXTURES, "calibre-demo.docx"));
  const result = await convertDocxToMarkdown(docxBuffer, {
    includeMeta: false,
  });

  // Should produce at least 5000 chars of markdown
  t.true(
    result.markdown.length > 5000,
    `output should be > 5000 chars, got ${result.markdown.length}`,
  );
});
