/**
 * mermaid-validator.ts
 *
 * Dynamically imports mermaid to validate ```mermaid fences.
 * Replaces invalid diagrams with an annotated warning.
 */

/**
 * Globals mermaid (really DOMPurify, via mermaid's label sanitizer) expects to
 * find. Without them `mermaid.parse` throws on any diagram carrying node
 * labels — `A[Start]`, `B{Choice}`, `-->|yes|` — which is most real diagrams.
 */
const DOM_GLOBALS = [
  "window",
  "document",
  "DocumentFragment",
  "Node",
  "Element",
  "HTMLElement",
  "HTMLTemplateElement",
  "SVGElement",
  "NodeFilter",
  "trustedTypes",
  "navigator",
] as const;

type Restore = () => void;

/** Nothing to undo — a DOM was already present, or setup never happened. */
const NO_RESTORE: Restore = () => {
  /* intentionally empty */
};

/**
 * Install a headless DOM for the duration of validation, then put the global
 * scope back exactly as we found it. No-op when a DOM already exists (browser,
 * jsdom, or an earlier caller), so we never clobber someone else's environment.
 *
 * DOMPurify binds to the global scope when mermaid is first imported, so this
 * has to run *before* that import.
 */
async function installDom(): Promise<Restore> {
  const scope = globalThis as unknown as Record<string, unknown>;
  if (scope.window !== undefined) return NO_RESTORE;

  const { Window } = await import("happy-dom-without-node");
  // Constructing a happy-dom Window replaces globalThis.process. Put the real
  // one back immediately — losing it breaks anything that later reads
  // process.exit, argv, or env (see the same dance in markdown-parser.ts).
  const originalProcess = scope.process;
  const win = new Window({ url: "https://example.com" }) as unknown as Record<
    string,
    unknown
  >;
  if (originalProcess !== undefined) scope.process = originalProcess;

  const had = new Map<string, boolean>();
  const saved = new Map<string, unknown>();
  for (const key of DOM_GLOBALS) {
    had.set(key, key in scope);
    saved.set(key, scope[key]);
  }

  const assign = (key: string, value: unknown) => {
    try {
      scope[key] = value;
    } catch {
      // Some globals (navigator) are getter-only on newer Node versions.
      Object.defineProperty(scope, key, {
        value,
        configurable: true,
        writable: true,
      });
    }
  };

  assign("window", win);
  for (const key of DOM_GLOBALS) {
    if (key === "window") continue;
    const value = win[key];
    if (value !== undefined) assign(key, value);
  }

  return () => {
    for (const key of DOM_GLOBALS) {
      if (had.get(key)) assign(key, saved.get(key));
      else {
        try {
          delete scope[key];
        } catch {
          assign(key, undefined);
        }
      }
    }
  };
}

/**
 * Did mermaid actually reject the diagram's syntax, or did it fall over for an
 * environmental reason? Only the former justifies annotating the user's
 * document — a missing DOM API is our problem, not theirs, and claiming
 * "invalid syntax" over it would be worse than staying quiet.
 */
function isSyntaxError(message: string): boolean {
  return /parse error|no diagram type detected|expecting|lexical error|syntax error/i.test(
    message,
  );
}

let warnedAboutEnvironment = false;

export async function validateMermaid(markdown: string): Promise<string> {
  // Note: This regex expects strict 3-backtick, non-indented fences typically
  // generated by LLMs. Indented fences may slip through unvalidated.
  const mermaidFencesRegex = /```mermaid\r?\n([\s\S]*?)\r?\n```/g;

  // If there are no mermaid blocks, we can return early
  if (!markdown.includes("```mermaid")) {
    return markdown;
  }

  // biome-ignore lint/suspicious/noExplicitAny: dynamic import
  let mermaid: any;
  let restoreDom: Restore = NO_RESTORE;
  try {
    // Must precede the mermaid import — DOMPurify binds to the global scope there.
    restoreDom = await installDom();
    // Dynamically import mermaid. If it's missing or fails, we catch the error below.
    const mod = await import("mermaid");
    mermaid = mod.default || mod;
    // Suppress console.error/warn from mermaid parser since we handle errors
    mermaid.initialize({ startOnLoad: false, suppressErrorRendering: true });
  } catch (err: unknown) {
    restoreDom();
    const error = err as Error;
    console.warn(
      `[get-md] Mermaid validation is enabled, but mermaid package could not be loaded: ${error.message}`,
    );
    // If we can't load mermaid, we just return the unmodified markdown.
    return markdown;
  }

  // We will process blocks asynchronously, so we find all matches first
  const blocks: {
    fullMatch: string;
    content: string;
    startIndex: number;
    endIndex: number;
  }[] = [];

  let match = mermaidFencesRegex.exec(markdown);
  while (match !== null) {
    blocks.push({
      fullMatch: match[0],
      content: match[1],
      startIndex: match.index,
      endIndex: match.index + match[0].length,
    });
    match = mermaidFencesRegex.exec(markdown);
  }

  if (blocks.length === 0) {
    restoreDom();
    return markdown;
  }

  let result = markdown;
  try {
    // Process backwards to not mess up indices when replacing
    for (let i = blocks.length - 1; i >= 0; i--) {
      const block = blocks[i];
      try {
        // Validate the syntax.
        // mermaid.parse returns true/false or a diagram object, or throws an error.
        await mermaid.parse(block.content);
      } catch (err: unknown) {
        const error = err as Error;
        const message = error.message?.split("\n")[0] || "Unknown error";

        // Only a genuine syntax complaint earns an annotation. Anything else
        // (a DOM API mermaid wanted and we could not provide, a lazily loaded
        // parser chunk failing to initialize) is our problem — say so on
        // stderr once and leave the author's diagram untouched.
        if (!isSyntaxError(message)) {
          if (!warnedAboutEnvironment) {
            warnedAboutEnvironment = true;
            console.warn(
              `[get-md] Mermaid validation could not run for at least one block and was skipped: ${message}`,
            );
          }
          continue;
        }

        // Prevent duplicate warnings by detecting Mermaid blocks that have
        // already been annotated by the validator before injecting another warning.
        const textBefore = result.substring(
          Math.max(0, block.startIndex - 150),
          block.startIndex,
        );
        if (textBefore.includes("> [!WARNING]\n> Invalid Mermaid syntax")) {
          continue;
        }

        const warningMessage = `> [!WARNING]\n> Invalid Mermaid syntax: ${message}`;
        const replacement = `\n${warningMessage}\n\n${block.fullMatch}\n`;
        result =
          result.substring(0, block.startIndex) +
          replacement +
          result.substring(block.endIndex);
      }
    }
  } finally {
    restoreDom();
  }

  return result;
}
