/**
 * mermaid-validator.ts
 *
 * Dynamically imports mermaid to validate ```mermaid fences.
 * Replaces invalid diagrams with an annotated warning.
 */

export async function validateMermaid(markdown: string): Promise<string> {
  // Note: This regex expects strict 3-backtick, non-indented fences typically
  // generated by LLMs. Indented fences may slip through unvalidated.
  const mermaidFencesRegex = /```mermaid\r?\n([\s\S]*?)\r?\n```/g;

  // If there are no mermaid blocks, we can return early
  if (!markdown.includes("```mermaid")) {
    return markdown;
  }

  // biome-ignore lint/suspicious/noExplicitAny: dynamic import
  let mermaid: any;
  try {
    // Dynamically import mermaid. If it's missing or fails, we catch the error below.
    const mod = await import("mermaid");
    mermaid = mod.default || mod;
    // Suppress console.error/warn from mermaid parser since we handle errors
    mermaid.initialize({ startOnLoad: false, suppressErrorRendering: true });
  } catch (err: unknown) {
    const error = err as Error;
    console.warn(
      `[get-md] Mermaid validation is enabled, but mermaid package could not be loaded: ${error.message}`,
    );
    // If we can't load mermaid, we just return the unmodified markdown.
    return markdown;
  }

  // We will process blocks asynchronously, so we find all matches first
  const blocks: {
    fullMatch: string;
    content: string;
    startIndex: number;
    endIndex: number;
  }[] = [];

  let match = mermaidFencesRegex.exec(markdown);
  while (match !== null) {
    blocks.push({
      fullMatch: match[0],
      content: match[1],
      startIndex: match.index,
      endIndex: match.index + match[0].length,
    });
    match = mermaidFencesRegex.exec(markdown);
  }

  if (blocks.length === 0) {
    return markdown;
  }

  let result = markdown;
  // Process backwards to not mess up indices when replacing
  for (let i = blocks.length - 1; i >= 0; i--) {
    const block = blocks[i];
    try {
      // Validate the syntax.
      // mermaid.parse returns true/false or a diagram object, or throws an error.
      await mermaid.parse(block.content);
    } catch (err: unknown) {
      const error = err as Error;
      // It's invalid!

      // Prevent duplicate warnings by detecting Mermaid blocks that have
      // already been annotated by the validator before injecting another warning.
      const textBefore = result.substring(
        Math.max(0, block.startIndex - 150),
        block.startIndex,
      );
      if (textBefore.includes("> [!WARNING]\n> Invalid Mermaid syntax")) {
        continue;
      }

      const warningMessage = `> [!WARNING]\n> Invalid Mermaid syntax: ${error.message?.split("\n")[0] || "Unknown error"}`;
      const replacement = `\n${warningMessage}\n\n${block.fullMatch}\n`;
      result =
        result.substring(0, block.startIndex) +
        replacement +
        result.substring(block.endIndex);
    }
  }

  return result;
}
